spring:
  application:
    name: MenuDisplay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbq.magilhub.com:3306/mhq
    username: mhqsvc
    password: jz46DzYp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
